version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    working_directory: /home/circleci/hola    
    steps:
      - checkout
      - run: python3 -m venv env
      - run: ./env/bin/pip install -e .

workflows:
  main:
    jobs:
      - build
